# Generated by Django 4.1.7 on 2023-03-28 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tasklistModel',
            new_name='tasklist',
        ),
    ]
