# Generated by Django 4.1.7 on 2023-03-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticationApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth',
        ),
    ]
